Examine how different models interact/react with 3 years of fantasy premeir league points.

In [2]:
# Import important libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Load the dataset

The target value is 
goals_scored

Feature values are 
assists, attempted passes, big_chances_created, big_chances_missed, bonus, bps, clean_sheets, clearances_blocks_interceptions, completed_passes, creativity, dribbles, ea_index, element, errors_leading_to_goal, errors_leading_to_goal_attempt, fixture, fouls, goals_conceded

In [4]:
# Load the dataset
dataset = pd.read_csv('complete_gws.csv', encoding="ISO-8859-1")

X = dataset.iloc[:67936,1:19].values
y = dataset.iloc[:67936,19].values
print (X,y)

[[0 0 0 ... 10 0 0]
 [0 3 0 ... 3 0 0]
 [0 26 0 ... 8 0 3]
 ...
 [0 0 0 ... 81 0 0]
 [0 0 0 ... 83 0 0]
 [0 31 0 ... 84 2 2]] [0 0 0 ... 0 0 0]


In [3]:
# Curious about how many teams there are and instances tied to them
# See if a player has a better/worse chance of 
# scoring against a specific team

dataset.groupby('element').size()
dataset.sort_values(by='opponent_team')

name  assists  attempted_passes  \
72783            Ørjan_Nyland_27        0                 0   
69731     Isaac_Success Ajayi_365        0                 0   
69732           Ismaïla_Sarr_525        0                 0   
69733               Issa_Diop_381        0                 2   
69734          Ivan_Cavaleiro_419        0                 0   
69735            Jack_Colback_482        0                 0   
69736               Jack_Cork_102        0                 0   
69738          Jack_O'Connell_293        0                 0   
69739             Jack_Simpson_66        0                 0   
69740             Jack_Stacey_446        0                 0   
69741           Jack_Stephens_308        0                 0   
69742           Jack_Wilshere_394        0                 0   
69743            Jacob_Murphy_483        0                 0   
69744           Jake_Eastwood_299        0                 0   
69745        Jamaal_Lascelles_258        0                 0   
69746             Jamal_Lewis_276        0                 0   
69729         Ilkay_Gündogan_222        0                 0   
69728           Idrissa_Gueye_156        0                 0   
69727          Ibrahim_Amadou_507        0                 0   
69726           Hélder_Costa_418        0                 0   
69707         Gerard_Deulofeu_363        0                 0   
69708        Giovani_Lo Celso_523        0                 0   
69709             Glenn_Murray_44        0                 0   
69710          Grady_Diangana_398        0                 0   
69712            Grant_Hanley_277        0                 0   
69713        Gylfi_Sigurdsson_151        1                 0   
69714         Hamza_Choudhury_180        0                 0   
69747            James_Chester_23        0                 0   
69715              Harry_Kane_338        0                 0   
69719           Harvey_Barnes_172        0                 0   
...                           ...      ...               ...   
6894                  Joshua_King        0                19   
45939              Markus_Suttner        0                 0   
23913               Jesse_Lingard        0                 4   
34134              Connor_Goldson        0                 0   
45949                 Mathew_Ryan        0                28   
16124  Michael_Sim�es Domingues        0                 0   
17017              Tyias_Browning        0                 0   
3849                 Joseph_Gomez        0                 0   
10924       S�bastien_Pocognoli        0                 0   
34103           Bruno_Saltor Grau        0                 0   
45994          Niki_M�enp��        0                 0   
3840             Jordan_Henderson        0               106   
18495              Alberto_Moreno        0                 0   
46001              Oliver_Norwood        0                 0   
34095                 Beram_Kayal        0                 1   
62927              Ben_Wilmot_544        0                 0   
46009               Pascal_Gro�        1                29   
62921              Ben_Foster_445        0                23   
20036                Robbie_Brady        0                16   
6907             Junior_Stanislas        0                 0   
3821                   Joel_Matip        0                85   
46056                 Sam_Baldock        0                 0   
34066           Anthony_Knockaert        0                34   
17012                  Tom_Davies        0                28   
46076                 Shane_Duffy        0                31   
62885              Andre_Gray_395        0                21   
46085               Solomon_March        0                 6   
46094               Steve_Sidwell        0                 0   
20046             Rouwen_Hennings        0                 0   
56994            Chris_Mepham_580        0                49   

       big_chances_created  big_chances_missed  bonus  bps  

Splitting the data into training (70%) and testing (30%)

In [4]:
from sklearn.model_selection import train_test_split

# Splitting the data into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

Fit multiple linear regression to the dataset

In [5]:
# Fitting Multiple linear regression to training set
from sklearn.linear_model import LinearRegression

mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

print(y_test)

# Calculate the error
from sklearn import metrics

print(metrics.mean_squared_error(y_test, y_pred))

[0 0 0 ... 0 0 0]
0.0197327885259019


Multiple logistic regression models

In [6]:
#Fitting Logistic Regression to Training Set
from sklearn.linear_model import LogisticRegression
classifierObj = LogisticRegression(random_state=0)
classifierObj.fit(X_train, y_train)

#Normalizing the features
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Make a prediction
y_pred = classifierObj.predict(X_test)

# Find the misclassification rate
from sklearn import metrics
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

print(cm)

print(classifierObj.score(X_test,y_test))

/Users/suyash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/suyash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[19239   262     0     9     9]
 [  697    65     0     3     0]
 [   73    10     3     2     0]
 [    7     1     0     0     0]
 [    1     0     0     0     0]]
0.9473038614395761
